package com.dentica.v15;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.text.InputType;import android.view.*;import android.widget.*;import java.net.*;import java.io.*;import org.json.*;
public class MainActivity extends Activity{
 LinearLayout c; String API=BuildConfig.API_BASE_URL; SharedPreferences sp;
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(18,14,18,10);v.setTextColor(Color.WHITE);return v;}
 Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);return x;} EditText in(String h){EditText x=new EditText(this);x.setHint(h);return x;}
 public void onCreate(Bundle x){super.onCreate(x);sp=getSharedPreferences("dentica",0);home();}
 void base(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.setBackgroundColor(Color.rgb(7,21,27));r.addView(t("DENTICA • V15",24));ScrollView s=new ScrollView(this);c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);s.addView(c);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));LinearLayout n=new LinearLayout(this);for(String q:new String[]{"الرئيسية","الحجز","الخدمات","الإدارة"}){Button z=b(q);z.setOnClickListener(v->{if(q.equals("الرئيسية"))home();else if(q.equals("الحجز"))booking();else if(q.equals("الخدمات"))services();else admin();});n.addView(z,new LinearLayout.LayoutParams(0,65,1));}r.addView(n);setContentView(r);}
 void home(){base();c.addView(t("DENTICA",32));c.addView(t("عيادة أسنان • Cloudflare D1 • Full Control",18));Button z=b("📅 حجز موعد");z.setOnClickListener(v->booking());c.addView(z);Button a=b("🔐 دخول الإدارة");a.setOnClickListener(v->login());c.addView(a);}
 void booking(){base();c.addView(t("حجز موعد",26));EditText n=in("اسم المريض"),p=in("رقم الهاتف"),d=in("التاريخ والوقت"),m=in("ملاحظات");c.addView(n);c.addView(p);c.addView(d);c.addView(m);Button z=b("تأكيد الحجز");z.setOnClickListener(v->req("POST","/api/appointments","{\"name\":\""+esc(n.getText().toString())+"\",\"phone\":\""+esc(p.getText().toString())+"\",\"appointment_date\":\""+esc(d.getText().toString())+"\",\"notes\":\""+esc(m.getText().toString())+"\"}",false,s->toast("تم إرسال الحجز")));c.addView(z);}
 void services(){base();c.addView(t("الخدمات",26));req("GET","/api/services",null,false,s->{try{JSONArray a=new JSONArray(s);for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);c.addView(t("🦷 "+o.optString("name")+"\n"+o.optString("description")+"\nالسعر: "+o.optDouble("price"),17));}}catch(Exception e){toast("خطأ");}});}
 void login(){base();c.addView(t("دخول الإدارة",26));EditText e=in("البريد الإلكتروني"),p=in("كلمة المرور");p.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);c.addView(e);c.addView(p);Button z=b("دخول");z.setOnClickListener(v->req("POST","/api/admin/login","{\"email\":\""+esc(e.getText().toString())+"\",\"password\":\""+esc(p.getText().toString())+"\"}",false,s->{try{JSONObject o=new JSONObject(s);if(o.has("token")){sp.edit().putString("token",o.getString("token")).apply();admin();}else toast(o.optString("error","فشل الدخول"));}catch(Exception x){toast("فشل الدخول");}}));c.addView(z);}
 boolean logged(){return !sp.getString("token","").isEmpty();}
 void admin(){if(!logged()){login();return;}base();c.addView(t("لوحة التحكم — تحكم كامل",26));req("GET","/api/dashboard",null,true,s->c.addView(t("📊 "+s,15)));String[] a={"patients|👥 المرضى","doctors|👨‍⚕️ الأطباء","services|🦷 الخدمات","appointments|📅 المواعيد"};for(String q:a){String[] x=q.split("\\|",2);Button z=b(x[1]);z.setOnClickListener(v->crud(x[0]));c.addView(z);}Button st=b("⚙️ إعدادات العيادة");st.setOnClickListener(v->settings());c.addView(st);Button out=b("تسجيل الخروج");out.setOnClickListener(v->req("POST","/api/admin/logout","{}",true,s->{sp.edit().remove("token").apply();home();}));c.addView(out);}
 void crud(String type){base();c.addView(t("إدارة "+type,24));Button add=b("＋ إضافة");add.setOnClickListener(v->form(type,null));c.addView(add);req("GET","/api/"+type,null,true,s->{try{JSONArray a=new JSONArray(s);for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);int id=o.optInt("id");String label=type.equals("patients")?o.optString("name")+" — "+o.optString("phone"):type.equals("doctors")?o.optString("name")+" — "+o.optString("specialty"):type.equals("services")?o.optString("name")+" — "+o.optDouble("price"):o.optString("appointment_date")+" — "+o.optString("patient");c.addView(t("#"+id+"  "+label,16));Button ed=b("تعديل #"+id);ed.setOnClickListener(v->form(type,o));c.addView(ed);Button del=b("حذف #"+id);del.setOnClickListener(v->req("DELETE","/api/"+type,"{\"id\":"+id+"}",true,s2->{toast("تم الحذف");crud(type);}));c.addView(del);}}catch(Exception e){toast("تعذر تحميل البيانات");}});}
 void form(String type,JSONObject old){base();c.addView(t(old==null?"إضافة":"تعديل",24));String[] hs=type.equals("patients")?new String[]{"name","phone","email","notes"}:type.equals("doctors")?new String[]{"name","specialty","phone"}:type.equals("services")?new String[]{"name","description","price"}:new String[]{"patient_id","doctor_id","service_id","appointment_date","status","notes"};EditText[] f=new EditText[hs.length];for(int i=0;i<hs.length;i++){f[i]=in(hs[i]);if(old!=null)f[i].setText(old.optString(hs[i],""));c.addView(f[i]);}Button save=b("حفظ");save.setOnClickListener(v->{try{JSONObject o=old==null?new JSONObject():new JSONObject(old.toString());for(int i=0;i<hs.length;i++)o.put(hs[i],f[i].getText().toString());req(old==null?"POST":"PUT","/api/"+type,o.toString(),true,s->{toast("تم الحفظ");crud(type);});}catch(Exception e){toast("بيانات غير صحيحة");}});c.addView(save);}
 void settings(){base();c.addView(t("إعدادات العيادة",24));req("GET","/api/settings",null,true,s->{try{JSONArray a=new JSONArray(s);for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);EditText v=in(o.optString("key"));v.setText(o.optString("value"));c.addView(v);Button z=b("حفظ "+o.optString("key"));z.setOnClickListener(x->req("POST","/api/settings","{\"key\":\""+esc(o.optString("key"))+"\",\"value\":\""+esc(v.getText().toString())+"\"}",true,y->toast("تم الحفظ")));c.addView(z);}}catch(Exception e){toast("خطأ");}});}
 interface CB{void ok(String s);} void req(String method,String path,String data,boolean auth,CB cb){new Thread(()->{try{HttpURLConnection h=(HttpURLConnection)new URL(API+path).openConnection();h.setRequestMethod(method);h.setRequestProperty("Content-Type","application/json");String tok=sp.getString("token","");if(auth&&!tok.isEmpty())h.setRequestProperty("Authorization","Bearer "+tok);if(data!=null){h.setDoOutput(true);h.getOutputStream().write(data.getBytes("UTF-8"));}int code=h.getResponseCode();InputStream in=code>=400?h.getErrorStream():h.getInputStream();BufferedReader r=new BufferedReader(new InputStreamReader(in,"UTF-8"));StringBuilder s=new StringBuilder();String l;while((l=r.readLine())!=null)s.append(l);String out=s.toString();runOnUiThread(()->{if(code==401){sp.edit().remove("token").apply();login();}else cb.ok(out);});}catch(Exception e){toast("API غير متصل");}}).start();}
 void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_SHORT).show());}String esc(String x){return x.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n");}@Override public void onBackPressed(){home();}
}
